### ISSUE TITLE
QComponent init fails via exception or early return at not handled

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#151] opened 2020-12-09 00:52 UTC
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
QComponent (and subclasses) init fails via exception or early return at not handled 

### Steps to reproduce the problem

```
%autoreload 2


import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, open_docs

%metal_heading Welcome to Qiskit Metal!


design = designs.DesignPlanar()
gui = MetalGUI(design)

from qiskit_metal.components.qubits.transmon_pocket import TransmonPocket

design.delete_all_components()

options = dict(
    pad_width = '425 um', 
    pocket_height = '650um',
    connection_pads=dict(  # pin connecotrs
        a = dict(loc_W=+1,loc_H=+1), 
        b = dict(loc_W=-1,loc_H=+1, pad_height='30um'),
        c = dict(loc_W=+1,loc_H=-1, pad_width='200um'),
        d = dict(loc_W=-1,loc_H=-1, pad_height='50um')
    )
)

q1 = TransmonPocket(design, 'Q1', options = dict(pos_x='+0.5mm', pos_y='+0.5mm', **options))

design.delete_all_components() 
gui.rebuild() # refresh
````

### What is the expected behavior?
Some sort of GUI pop up alert 

### Suggested solutions
Pop up window

**Comment by JeremyDrysdale-ibm** [comment] 2021-08-11 11:41
Unable to reproduce - may have been resolved without closing the issue.  @grace-harper-ibm if this is unresolved please reopen.

**Closed by JeremyDrysdale-ibm** 2021-08-11 11:41 UTC
Labels: bug
