### ISSUE TITLE
Keep cursor in place when editing Param Entry Window

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#594] opened 2021-06-18 16:38 UTC
Please be as descriptive as possible, including: what is expected, why is this feature needed, what is the objective, etc.

### What is the feature being requested?
Currently, when you enter an argument into Param Entry Window, the cursor gets moved to the top of the window. 
Instead, keep the cursor wherever it last was

### What are use cases for this feature?
Ease of use

**Comment by zlatko-minev** [comment] 2021-09-29 22:46
To clarify a bit, the issue is when you open the dialog to create a new component, you see this 
![image](https://user-images.githubusercontent.com/15937254/135358651-f9137df1-8dc5-4ada-acd5-4f4479cb4734.png)

Then if you open the options and edit the name of some key, the focus of the cursor is lost and reset. 

Ideally, the cursor and highlight would stay where it is. This one is a minor feature update

**Comment by priti-ashvin-shah-ibm** [comment] 2023-02-01 21:37
Looks like this has merged by @ismirlia , will close.

**Closed by priti-ashvin-shah-ibm** 2023-02-01 21:37 UTC
Labels: bug, good first issue, open for contributions
