### ISSUE TITLE
Transmon analytics add to analysis toolbox

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-metal#218] opened 2021-01-20 15:19 UTC
### What is the feature being requested?
Add Jens Koch key formulas for Transmon analytics add to analysis toolbox (Koch 2007 Charge Offset Insensitive Qubit...)

[ ] Port my mathematica code over to python
[ ] Create a notebook to reproduce these plots 

![image](https://user-images.githubusercontent.com/15937254/105195425-9dc91880-5b08-11eb-9b27-7e6eccea8408.png)
![image](https://user-images.githubusercontent.com/15937254/105195437-a0c40900-5b08-11eb-99a0-64ae820102dc.png)
![image](https://user-images.githubusercontent.com/15937254/105195457-a7528080-5b08-11eb-8dc0-0bd4e4b029b6.png)

Heres my code in mathematica to do this, just port over to python
![image](https://user-images.githubusercontent.com/15937254/105195649-d49f2e80-5b08-11eb-8bc4-a44a1049eb78.png)

![image](https://user-images.githubusercontent.com/15937254/105195669-db2da600-5b08-11eb-981a-c340600f7340.png)
![image](https://user-images.githubusercontent.com/15937254/105195713-e5e83b00-5b08-11eb-8bb3-b9c5f50c4c24.png)

For the plots 
![image](https://user-images.githubusercontent.com/15937254/105195577-c3562200-5b08-11eb-8954-759e44dc9068.png)

**Comment by nalanzil** [comment] 2021-04-02 20:38
> 
> 
> This can be done easily in my analytic modelling of the transmon I have done in python. I can do a notebook to reproduce the plots to show how the code is used.

Do you think you are still able to do this, @warrench ? It looks like the calculation of the mathieu characteristic values in scipy is problematic (apparently a documented problem: https://github.com/scipy/scipy/issues/3075) so another approach seems to be necessary.

**Comment by warrench** [comment] 2021-04-02 20:53
The way that the Mathieu functions are implemented are by solving the Mathieu equations. Whatever program you are using is solving it numerically in some way. Likely some variation of https://dl.acm.org/doi/10.1145/155743.155796

I do not use scipy to use their version of the Mathieu equation. The problem directly maps onto diagonalizing a tridiagonal matrix. This is already committed in the analysis section and it is working.

https://github.com/Qiskit/qiskit-metal/blob/main/qiskit_metal/analyses/hamiltonian/transmon_charge_basis.py

This is also easily implemented with Jens Koch's scqubit package

https://scqubits.readthedocs.io/en/latest/

I guess the issue is to create a notebook for it. Of which I can do it when I have time, but I don't know if it needs to be included in a tutorial or not or where this would be placed.

**Comment by zlatko-minev** [comment] 2021-04-03 05:41
I do plan to add scqubits as a dependency to Metal in the coming month or so 

 

From: warrench ***@***.***>
Reply-To: Qiskit/qiskit-metal ***@***.***>
Date: Friday, April 2, 2021 at 1:54 PM
To: Qiskit/qiskit-metal ***@***.***>
Cc: Zlatko Minev ***@***.***>, Author ***@***.***>
Subject: Re: [Qiskit/qiskit-metal] Transmon analytics add to analysis toolbox (#218)

 

The way that the Mathieu functions are implemented are by solving the Mathieu equations. Whatever program you are using is solving it numerically in some way. Likely some variation of https://dl.acm.org/doi/10.1145/155743.155796

I do not use scipy to use their version of the Mathieu equation. The problem directly maps onto diagonalizing a tridiagonal matrix. This is already committed in the analysis section and it is working.

https://github.com/Qiskit/qiskit-metal/blob/main/qiskit_metal/analyses/hamiltonian/transmon_charge_basis.py

This is also easily implemented with Jens Koch's scqubit package

https://scqubits.readthedocs.io/en/latest/

I guess the issue is to create a notebook for it. Of which I can do it when I have time, but I don't know if it needs to be included in a tutorial or not or where this would be placed.

**Closed** 2021-04-26 14:00 UTC
Labels: analysis: quantum, documentation & tutorials, enhancement, good first issue, needs help
