### ISSUE TITLE
Remove Developer Mode

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#582] opened 2021-06-15 20:36 UTC
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Developer Mode is less used than Jupyter Notebook imports and clunkier

**Comment by JeremyDrysdale-ibm** [comment] 2021-06-16 12:36
@grace-harper-ibm Is this a duplicate of #513?  If not, how it is different?

**Closed** 2021-06-18 14:53 UTC
Labels: bug
